# mkdocs.yml
site_name: Proof of Post Docs
site_url: https://CardanoTokenIO.github.io/ProoOfPost/
theme:
  name: material
  logo: images/utxo-maestro-logo.jpg
  favicon: images/TokenLogo.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.sections
    - content.code.copy
    - search.suggest
    - search.highlight
    - navigation.expand
    - palette.toggle

# Use docs directory to avoid conflicts
docs_dir: docs

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - def_list
  - footnotes
  - attr_list
  - md_in_html

# Build navigation based on existing SUMMARY.md structure
nav:
  - Home: README.md
  - Platform Overview:
    - What is Proof of Post?: platform/what-is-proof-of-post.md
    - Key Features: platform/key-features.md
    - Technical Architecture: platform/technical-architecture.md
  - Tokenomics:
    - The POST Token: getting-started/the-post-token.md
    - Presale: getting-started/presale.md
  - Core Features:
    - Social Media Features: features/social-media.md
    - Wallet Integration: features/wallet-integration.md
    - Token Ecosystem: features/token-ecosystem.md
    - Content Monetization: features/content-monetization.md
  - User Guide:
    - Getting Started: user-guide/getting-started.md
    - Creating Content: user-guide/creating-content.md
    - Wallet Connection: user-guide/wallet-connection.md
    - Monetizing Content: user-guide/monetizing-content.md
  - Developer Resources:
    - API Documentation: developers/api-documentation.md
  - Community:
    - Social Links: social/links.md

extra:
  generator: false
